# version 2 of rtd, 1 is deprecated
version: 2


build:
  # python 3.9 is built in ubuntu, this isn't about the package development
  os: "ubuntu-20.04"
  tools:
    python: "3.9"


python:
  install:
    - method: pip
      path: .


# make it more obvious when an rtd build fails
sphinx:
  fail_on_warning: true


# documentation already available as HTML, this will allow it to be downloaded as other formats
formats:
  - pdf
  - epub